# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.6
_src_path: https://github.com/jupyterlab/extension-template
author_email: xishizhu1@gmail.com
author_name: Ethan
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: frontend
labextension_name: myextension
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension.
python_name: myextension
repository: https://github.com/SAIL-UA/CAST.git
test: false
viewer_name: ''

